---
 - name: Initialized cluster
   shell: "{{ bin_dir }}/initdb --data-checksums --pgdata={{ database_dir }}"
   when:  yum_result.changed
   notify:
     - start postgres
 - name: registre shared buffers
   shell: free -m|awk '/^Mem:/{print $2}'| xargs -I {} echo "{}/100*30"|bc
   register: shared_buffers 
 - name: Change replication in pg_hba.conf
   lineinfile: dest=/data/db/pg_hba.conf line="host replication {{ rep_user }} {{ item }}/32 {{ auth_metod }}"
   with_items:
    - "{{ groups['master'] }}"
    - "{{ groups['slave'] }}"
 - name: Change Permission Connect in pg_hba.conf 
   lineinfile: dest=/data/db/pg_hba.conf line="host all all 10.0.0.0/8 {{ auth_metod }}" insertafter="^host\s+?all\s+?all\s+?127.0.0.1/32\s+?trust"
 - name: Change Permission Connect in pg_hba.conf 
   lineinfile: dest=/data/db/pg_hba.conf line="host all postgres 10.0.0.0/8 {{ auth_metod }}" insertafter="^host\s+?all\s+?all\s+?127.0.0.1/32\s+?trust"
 - name: Configigure postgresql.conf
   template: src=postgresql.conf.j2 dest=/data/db/postgresql.conf owner={{ prog_user }} group={{ prog_user }} 
 

