---
- name: 'Install master'
  hosts: master 
  become: yes
  become_method: sudo
  become_user: root 
  ignore_errors: yes
  roles:
     - master_postgres

- name: 'Install slave'
  hosts: slave 
  become: yes
  become_method: sudo
  become_user: root
  ignore_errors: yes
  roles:
     - slave_postgres
