---
 postgres_ver: 9.4
 postgres_repo_url: http://yum.postgresql.org/{{ postgres_ver }}/redhat/rhel-6-x86_64/pgdg-redhat{{ postgres_ver |replace ('.','')  }}-{{ postgres_ver }}-1.noarch.rpm
 prog_user: postgres
 bin_dir: /usr/pgsql-{{ postgres_ver }}/bin/
 mount_disk_name: LvData
 mount_point: /data
 database_dir: "{{ mount_point }}/db"
 vg_name: postgresdb
 pv_disk: 
    - sdb
    - sdc
 lv_disk:
    - { name: "{{ mount_disk_name }}", size: '2g' }
    - { name: 'LvData1', size: '2g' }
 data_dir:
    - { dir: '{{ mount_point }}/logs/analyze', perm: '0775'}
    - { dir: '{{ database_dir }}', perm: '0700'}
 rep_user: rep
 auth_metod: trust
####CONFIG FILE
 conf_conn_number: 100 
 conf_super_conn_number: 10
 conf_temp_buffer: 128MB
 conf_wokr_mem: 2000MB
 conf_maintenance_work_mem: 200MB
