---
 - name: Validate Number of Nodes
   fail: msg="The number of nodes must be exactly 1!"
   when: num_master | int != 1
 - name: Initialized cluster
   shell: "{{ bin_dir }}/initdb --data-checksums --pgdata={{ database_dir }}"
   when:  yum_result.changed
 - name: registre shared buffers
   shell: free -m|awk '/^Mem:/{print $2}'| xargs -I {} echo "{}/100*30"|bc
   register: conf_shared_buffers 
 - name: registre shared buffers
   shell: free -m|awk '/^Mem:/{print $2}'| xargs -I {} echo "{}/100*60"|bc
   register: conf_effective_cache_size 
 - name: Change replication in pg_hba.conf
   lineinfile: dest={{ database_dir }}/pg_hba.conf line="host replication {{ rep_user }} {{ item }}/32 {{ auth_metod }}"
   with_items:
    - "{{ groups['master'] }}"
    - "{{ groups['slave'] }}"
 - name: Change Permission Connect in pg_hba.conf 
   lineinfile: dest={{ database_dir }}/pg_hba.conf line="host all all 10.0.0.0/8 {{ auth_metod }}" insertafter="^host\s+?all\s+?all\s+?127.0.0.1/32\s+?trust"
 - name: Change Permission Connect in pg_hba.conf 
   lineinfile: dest={{ database_dir  }}/pg_hba.conf line="host all postgres 10.0.0.0/8 {{ auth_metod }}" insertafter="^host\s+?all\s+?all\s+?127.0.0.1/32\s+?trust"
 - name: Configigure postgresql.conf
   template: src=postgresql.conf.j2 dest={{ database_dir  }}/postgresql.conf owner={{ prog_user }} group={{ prog_user }} 
 - name: Start postgres
   service: name=postgresql-{{ postgres_ver }} state=started
   when: yum_result.changed
   become_user: root
 - name: Add user for replication
   postgresql_user: name={{ rep_user  }} password={{ rep_pass }} role_attr_flags=replication encrypted=yes
 

